### ISSUE TITLE
Error: Cannot find module 'eslint-config-standard-jsx' from ...

### ISSUE THREAD

**Issue by chenxsan** [feross/standard#406]
After updated standard to 6.0.1, I got this error:

<img width="1027" alt="screen shot 2016-02-06 at 15 55 56" src="https://cloud.githubusercontent.com/assets/1091472/12865549/4e21b3a2-ccea-11e5-8be2-640921303a63.png">
I tested it on both Mac OSX and Windows 7.

But the module was installed under standard package:

<img width="459" alt="screen shot 2016-02-06 at 16 00 02" src="https://cloud.githubusercontent.com/assets/1091472/12865572/cc76131a-ccea-11e5-92ad-c49ee9a0f8e1.png">

I'm not sure what's going on here.

**Comment by matjaz** [comment]
+1
On node 4 I also get this error https://travis-ci.org/matjaz/stdin2/jobs/107404558
On node 5 it looks like a bug `Expected parentheses around arrow function argument.` https://travis-ci.org/matjaz/stdin2/jobs/107404555

**Comment by ngoldman** [comment]
I can confirm this error locally in node 4.x, 0.12, 0.10. Appears to work fine in 5.x. Might be related to differences between npm 2.x and 3.x? See https://travis-ci.org/ngoldman/module-init/jobs/107410146 for an example of the error recorded by travis-ci.

**Comment by ngoldman** [comment]
@matjaz I think it's working fine in node 5 in your case too: https://github.com/matjaz/stdin2/blob/master/test/index.js#L10

This is related to a [rule change](https://github.com/feross/standard/blob/master/CHANGELOG.md#new-rules) in standard 6:

> Require parens in arrow function arguments  ([#309](https://github.com/feross/standard/issues/309)) ([arrow-parens](http://eslint.org/docs/2.0.0/rules/arrow-parens.html))

**Comment by ngoldman** [comment]
So as far as I can this passes in node 5 because 5 is bundled with npm 3, which installs `eslint-config-standard-jsx` in the root `node_modules` directory of the project. ESLint looks for the module in the root and everything is fine in this case. In all non-bleeding-edge cases, this is not fine, as the errors indicate.

```
Error: Cannot find module 'eslint-config-standard-jsx' from '/home/travis/build/matjaz/stdin2'
Error: Cannot find module 'eslint-config-standard-jsx' from '/Users/ng/dev/github/module-init'
```

I'm guessing this is an ESLint rc.0 bug creeping in with the new standard release. The `.eslintrc` in standard should be able to look for other modules to extend in the `node_modules` directory relative to its location in the dependency tree first, rather than going straight to the `${process.cwd()}/node_modules` directory, failing, then giving up, right? Or something?

**Comment by chenxsan** [comment]
@ngoldman I'm using node 5.1.1 with npm 3.6.0.

**Comment by z0mt3c** [comment]
+1

**Comment by wraithan** [comment]
Node 5.5.0, tried with npm@latest and npm@2 both have the same issue. I'll give some other versions a shot if that would be valuable

**Comment by watson** [comment]
This seems to be an issue with version 2 of eslint where [it uses `process.cwd()` to resolve plugins](https://github.com/eslint/eslint/blob/11435afd76278a1291566c92af985bf8fad0731f/lib/config/config-file.js#L389-L394). I think this is also what's being discussed in eslint/eslint#5164.

I've tried to hack the current standard-engine codebase to overwrite the cwd temporarily and this seems to "fix" the problem ([here is where it calls eslint](https://github.com/Flet/standard-engine/blob/e78edc89c8af2c9486b20a44316374c52fabe259/index.js#L108))

**Comment by feross** [comment]
Sorry about this, everyone. This should be fixed in `standard` 6.0.3.

Thanks to everyone who helped debug this!

**Comment by feross** [comment]
I've opened an issue on `eslint` to fix the root cause of this issue: https://github.com/eslint/eslint/issues/5175
